= Cluster Samples Operator in Disconnected
include::_attributes.adoc[]

In a disconnected environment, the samples operator is removed. In order to make the samples available and transition to the `Managed` state, we must mirror and modify the corresponding images.

The images to mirror are in a configmap in Openshift:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get cm -n openshift-cluster-samples-operator imagestreamtag-to-image -o yaml
----

Steps to mirror:

- Create a `mapping.txt` with this script (`9-samples-mirroring.sh`). This script extract images from the configmap and create a `mapping.txt` file:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
include::example$9-samples-mirroring.sh[]
----

- and execute it like this:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
sh 9-samples-mirroring.sh ~/pull-secret-all.json
----

- Mirror with oc (or as an alternative with `oc-mirror` if you wish, you know how to do it ;) )
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc image mirror --skip-multiple-scopes=true --continue-on-error --insecure=true -a ./pull-secret-all.json -f mapping.txt
----

- Import the CA certificate of the registries (We have the `ca.crt` in the home directory because we downloaded it in the "Mirror Openshift Images" chapter) and add it as a trusted CA:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc create configmap custom-ca-registry --from-file=registry.dsal..8443=ca.crt -n openshift-config

oc patch image.config.openshift.io/cluster --patch '{"spec":{"additionalTrustedCA":{"name":"custom-ca-registry"}}}' --type=merge
----

- Probably your Samples Operator is in state `Removed`. To enable it again execute:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc patch config.samples.operator.openshift.io/cluster --patch  '{"spec":{"managementState":"Managed"}}' --type=merge
----

Now, you can see the samples in the Developer Console (https://console-openshift-console.apps.lab-test-disconnected.lab.dsal/samples/ns/default)
