kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 1
storageConfig:
  registry:
    imageURL: registry.dsal:8443/imagetset/mirror-disconnected:metadata
    skipTLS: true
mirror:
  platform:
    channels:
    - name: stable-4.11
      type: ocp
      minVersion: 4.11.20
      shortestPath: true
    architectures:
    - amd64

