kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 10
storageConfig:
  registry:
    imageURL: registry.dsal:8443/imagetset/mirror:metadata
    skipTLS: true
mirror:
  platform:
    channels:
    - name: stable-4.10
      type: ocp
      minVersion: 4.9.10
      maxVersion: 4.9.22
      shortestPath: true
    architectures:
    - amd64
