apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-karmab-registries
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,W1tyZWdpc3RyeV1dCiAgcHJlZml4ID0gIiIKICBsb2NhdGlvbiA9ICJxdWF5LmlvL2thcm1hYiIKICBtaXJyb3ItYnktZGlnZXN0LW9ubHkgPSBmYWxzZQoKW1tyZWdpc3RyeS5taXJyb3JdXQpsb2NhdGlvbiA9ICJyZWdpc3RyeS5kc2FsOjUwMDAva2FybWFiIgoKW1tyZWdpc3RyeS5taXJyb3JdXQpsb2NhdGlvbiA9ICJyZWdpc3RyeS5kc2FsOjg0NDMva2FybWFiIgo=
        filesystem: root
        mode: 420
        path: /etc/containers/registries.conf.d/99-karmab-registries.conf
