kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 10
storageConfig:
  registry:
    imageURL: registry.dsal:8443/imagetset/mirror-catalog:metadata
    skipTLS: true
mirror:
  additionalImages:
  - name: registry.redhat.io/redhat/redhat-operator-index:v4.11
  - name: registry.redhat.io/redhat/redhat-marketplace-index:v4.11
  - name: registry.redhat.io/redhat/community-operator-index:v4.11
  - name: registry.redhat.io/redhat/certified-operator-index:v4.11
