kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 10
storageConfig:
  registry:
    imageURL: registry.dsal:8443/imagetset/mirror-custom-catalog:metadata
    skipTLS: true
mirror:
  operators:
  - catalog: registry.dsal:8443/mirror/redhat/custom-redhat-operator-index:v1
    originalRef: registry.redhat.io/redhat/redhat-operator-index:v4.11
