kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 10
storageConfig:
  registry:
    imageURL: registry.dsal:8443/imagetset/mirror:metadata
    skipTLS: true
mirror:
  platform:
    channels:
    - name: stable-4.10
      type: ocp
      minVersion: 4.9.10
      maxVersion: 4.9.22
      shortestPath: true
    - name: stable-4.11
      type: ocp
      minVersion: 4.11.20
      maxVersion: 4.11.20
      shortestPath: true
    architectures:
    - amd64
  operators:
  - catalog: registry.dsal:8443/mirror/redhat/custom-redhat-operator-index:v1
    originalRef: registry.redhat.io/redhat/redhat-operator-index:v4.11
