apiVersion: batch/v1
kind: CronJob
metadata:
  name: insights-operator-cronjob
  namespace: openshift-insights
  annotations:
    config.openshift.io/inject-proxy: insights-operator
spec:
  schedule: "*/30 * * * *"          
  timeZone: Etc/UTC                
  concurrencyPolicy: "Replace"     
  startingDeadlineSeconds: 200     
  suspend: false                    
  successfulJobsHistoryLimit: 3    
  failedJobsHistoryLimit: 1        
  jobTemplate:                     
    spec:
      template:
        metadata:
          name: insights-operator-cronjob
          namespace: openshift-insights
          annotations:
            config.openshift.io/inject-proxy: insights-operator  
        spec:
          restartPolicy: OnFailure
          serviceAccountName: operator
          nodeSelector:
            kubernetes.io/os: linux
            node-role.kubernetes.io/master: ""
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
            operator: Exists
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
            tolerationSeconds: 900
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
            tolerationSeconds: 900
          volumes:
          - name: snapshots
            emptyDir: {}
          - name: service-ca-bundle
            configMap:
              name: service-ca-bundle
              optional: true
          initContainers:
          - name: gather-data
            image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:78e5a3b2244793c6d11b05332244ab5598b0b8c0332dd39b41a42913afc517e0
            terminationMessagePolicy: FallbackToLogsOnError
            volumeMounts:
            - name: snapshots
              mountPath: /var/lib/insights-operator
            - name: service-ca-bundle
              mountPath: /var/run/configmaps/service-ca-bundle
              readOnly: true
            ports:
            - containerPort: 8443
              name: https
            resources:
              requests:
                cpu: 10m
                memory: 70Mi
            args:
            - gather
            - -v=4
            - --config=/etc/insights-operator/server.yaml
          containers:
            - name: uploader
              image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0671b1b4e197c7a2673f9fbee100e5c1d76a49318fe436cabf2809279f4f5ce4
              env:
              - name: TOKEN
                value: "fasdfasdfasdfasdfas"
              - name: CLUSTERID
                value: "xxxx-xxxx-xxxx-xxxx"
              - name: HTTPS_PROXY
                value: "registry.dsal:3128"
              command:
              - /bin/sh
              args:
                - -c
                - 'sleep 30s && ls -d /var/lib/insights-operator/*gz && curl -v -H "User-Agent: insights-operator/one10time200gather184a34f6a168926d93c330 cluster/$(CLUSTERID)" -H "Authorization: Bearer $(TOKEN)" -F "upload=@$(ls -d /var/lib/insights-operator/*gz | head -n 1); type=application/vnd.redhat.openshift.periodic+tar" https://console.redhat.com/api/ingress/v1/upload'
              volumeMounts: [{name: snapshots, mountPath: /var/lib/insights-operator}]
